name: starter_template
version: 1.0.0

environment:
  sdk: ^2.17.0

dependencies:
  dart_appwrite: ^12.1.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  lints: ^2.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
